import = ["~/.config/alacritty/alacritty-theme/themes/ayu_dark.toml", "~/.config/alacritty/os.toml"]

[font]
size = 13

[font.bold]
family = "FiraMono Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "FiraMono Nerd Font"
style  = "Bold Italic"

[font.italic]
family = "FiraMono Nerd Font"
style  = "Italic"

[font.normal]
family = "FiraMono Nerd Font"
style  = "Regular"
