[window]
option_as_alt = "Both"

[[keyboard.bindings]]
action = "ReceiveChar"
key    = "K"
mods   = "Command"

# Search
[[keyboard.bindings]]
action = "ReceiveChar"
key    = "F"
mods   = "Command"

[[keyboard.bindings]]
action = "SearchForward"
key    = "F"
mode   = "~Search"
mods   = "Control"

[[keyboard.bindings]]
action = "ReceiveChar"
key    = "B"
mods   = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key    = "B"
mode   = "~Search"
mods   = "Control"

# font size
[[keyboard.bindings]]
action = "ReceiveChar"
key    = "0"
mods   = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key    = "-"
mods   = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key    = "+"
mods   = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key    = "="
mods   = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key    = "NumpadAdd"
mods   = "Command"

[[keyboard.bindings]]
action = "ReceiveChar"
key    = "NumpadSubtract"
mods   = "Command"

[[keyboard.bindings]]
action = "ResetFontSize"
key    = "0"
mods   = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key    = "-"
mods   = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key    = "+"
mods   = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key    = "="
mods   = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key    = "NumpadAdd"
mods   = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key    = "NumpadSubtract"
mods   = "Control"
