"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Pavan Kumar Sunkara"
email = "pavan.sss1991@gmail.com"

[ui]
editor = "nvim"
diff-editor = ":builtin"
default-command = "s"
graph.style = "square"

[colors]
change_id = "yellow"
"working_copy change_id" = "yellow"

[template-aliases]
builtin_log_compact = '''
if(root,
  format_root_commit(self),
  label(if(current_working_copy, "working_copy"),
    separate(" ",
      format_short_commit_header(self),
      if(empty, label("empty", "(empty)")),
      if(description,
        description.first_line(),
        label(if(empty, "empty"), description_placeholder),
      ),
    ),
  ),
)
'''

"format_short_commit_header(commit)" = '''
separate(" ",
  format_short_change_id_with_hidden_and_divergent_info(commit),
  format_short_commit_id(commit.commit_id()),
  commit.bookmarks(),
  commit.tags(),
  commit.working_copies(),
  if(commit.git_head(), label("git_head", "git_head()")),
  if(commit.conflict(), label("conflict", "conflict")),
  if(config("ui.show-cryptographic-signatures").as_boolean(),
    format_short_cryptographic_signature(commit.signature())
  ),
)
'''

[aliases]
s = ["status"]
lg = ["log", "-r", "root()::"]
bms = ["bookmark", "set", "--allow-backwards", "-r"]
